language: java
deploy:
  provider: releases
  api_key:
    secure: OoSdnK/EnAIiiM1N/YQH6KkUF6/qVUHL4dRXf5Pm1KgSVl2+bEFGR4tF465sPyzzhN8gkDiUeKs6RQFaOqa3kB7uT1kYmKJDaO1M5RQxe4uJk9x732w0f+kW3ynb2ANkNP2VrNrJTOWzyt/2RYncPT+nHaW3qAYs2+pa7Z5a7Y9st76T2o2WFzJwPt9S/4HpJCusVG+Bxhf5xyXOT7OcoZ9I42PsCqGV78TG4pWqnyIHp627OzcMZiJhmp0qablhrZZPCVXRaCzO+KifneiiAhRe1pTgZcUXA5t1ftFSd4CWsfZrtVseprMrZDBBcLNLm6ExWKVbf32geciin0UZFbVBiwm4wjuayZ9ZZPGazwJH/fzyhniwZsdmRCx+EHyQMSN+HPko4aluUGY6+zbokpxk5bpN4XXglbwBafiqzrRU+5aPfrTdgrtxC3sTpLW/2HVvlNOcoo7+ObdoSpBIL/sQzBAwhTLccwNRUPCOB5gZMZTyAJoJBXnHdgITR0aL/2PHyjsCRdMflrr92/+pLtgIXTMirRiZ87lffz+VDtLx8ATd483JjBcjSx5zG5+mSqMY9vinXW9vQ49lrEb13q2hCWGq7j0fyIDy/EUmzWxRC7UZYGIlpuWigMjMHHAYtPHxyBN5Bna76fmnwLnuQR6P5vik9fOAx0jSxKv2geA=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    repo: xebialabs-community/xld-elasticbeanstalk-plugin
    tags: true
